"use client";
import { useState } from "react";
import "./globals.scss";
import { Inter } from "next/font/google";
import { lightTheme, darkTheme } from "./theme/theme";
import { ThemeProvider, CssBaseline } from "@mui/material";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import Header from "./components/Header";
import Landing from "./components/Landing";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isDark, setIsDark] = useState(false);
  const [isLoggedIn, setIsLoggedIn] = useState(true);

  const switchTheme = () => {
    setIsDark(!isDark);
  };
  return (
    <html lang="en">
      <ThemeProvider theme={isDark ? darkTheme : lightTheme}>
        <LocalizationProvider dateAdapter={AdapterDayjs}>
          <CssBaseline />

          <body className={inter.className}>
            <Header switchTheme={switchTheme} />
            {!isLoggedIn ? <Landing /> : children}
            {/* <Landing /> */}
          </body>
        </LocalizationProvider>
      </ThemeProvider>
    </html>
  );
}
